# Generated by Django 4.2.7 on 2023-11-29 06:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 11, 47, 27, 594270)),
        ),
        migrations.AddField(
            model_name='category',
            name='is_offer_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
