# Generated by Django 4.2.7 on 2023-11-29 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_discount_category_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 12, 6, 14, 318575)),
        ),
    ]
