# Generated by Django 4.2.7 on 2023-11-29 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_discount_alter_category_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 12, 9, 43, 11205)),
        ),
    ]
