# Generated by Django 4.2.7 on 2023-11-29 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_discount_alter_category_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='start_date',
        ),
        migrations.AddField(
            model_name='category',
            name='minimum_amount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 12, 35, 37, 330996)),
        ),
    ]
