# Generated by Django 4.2.7 on 2023-11-30 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 29, 10, 52, 22, 957166)),
        ),
    ]
