# Generated by Django 4.2.7 on 2023-11-30 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_alter_category_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 29, 13, 16, 0, 251206)),
        ),
    ]
